# Generated by Django 4.0.5 on 2022-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_hashtag_post_hash_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default='instaperfect', max_length=100),
        ),
    ]
