# Generated by Django 4.0.5 on 2022-06-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
